[package]
name = "git-codeowners"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
color-eyre = "0.6.5"
ignore = "0.4.25"

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints.clippy]
all = "deny"
pedantic = "deny"
